export enum STORAGE_ENUM {
  COOKIE = 'COOKIE',
  SESSION = 'SESSION',
}

export enum COOKIE_STORAGE_ENUM {
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  ACCESS_EXPIRED_AT = 'ACCESS_EXPIRED_AT',
  REFRESH_EXPIRE_AT = 'REFRESH_EXPIRE_AT',
  USER_AGENT = 'USER_AGENT',
}

export enum REMEMBER_LOCAL_STORAGE_ENUM {
  EMAIL = 'REMEMBER_EMAIL',
  PASSWORD = 'REMEMBER_PASSWORD',
  INFO_UPDATE_USER = 'INFO_UPDATE_USER',
  INFO_ABOUT_USER = 'INFO_ABOUT_USER',
  INFO_INTEREST_USER = 'INFO_INTEREST_USER',
}

export enum VERIFY_EMAIL_ENUM {
  NAME = 'VERIFY_EMAIL_NAME',
  TIME = 'VERIFY_EMAIL_TIME',
  CODE = 'VERIFY_EMAIL_CODE',
  SOCIAL = 'VERIFY_EMAIL_SOCIAL',
}

export enum CONFIG_ENUM {
  POPUP_BANNER = 'CONFIG_POPUP_BANNER',
  NOTI = 'CONFIG_NOTI',
}
